dist: xenial
language: php
php:
    - 7.2
    - 7.3
before_script:
    - composer install --dev
script: vendor/bin/phpunit
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
