dist: xenial
language: php
php:
    - 7.3
    - 7.4
before_script:
    - sudo pecl install sqlite3
    - composer install --dev
script: phpunit
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
