dist: xenial
language: php
php:
    - 7.3
    - 7.4
before_install:
  - sudo apt-get update > /dev/null
install:
  - sudo apt-get install -y --force-yes php7.3-cgi php7.3-mysql php7.3-sqlite3 php7.4-cgi php7.4-mysql php7.4-sqlite3
before_script:
    - phpenv config-add ./sandbox/system/configurations/platform.ini
    - composer install --dev
script: phpunit
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
