dist: xenial
language: php
php:
    - 7.2
    - 7.3
before_install:
 - sudo apt-get update > /dev/null
install:
 - sudo apt-get install --force-yes phpunit
before_script:
    - composer install --dev
script: phpunit
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
