<?php
/**
 * @copyright Copyright (C) 2011-2012 The Platform Authors. All rights reserved.
 * @license   GNU/GPL, see LICENSE.php
 * Platform is free software. This version may have been modified pursuant
 * to the GNU General Public License, and as distributed it includes or
 * is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 * See COPYRIGHT.php for copyright notices and details.
 */
?>
<div class="footer">
  <p style="text-align: center" align="center">&copy; Copyright <a class="platform">The Platform Authors</a> <?php echo @date('Y') ?> <br /> Hosted by <a href="http://www.entilda.com"><strong>entilda</strong></a><br /> All Rights Reserved.</p>
</div>
<a class="logo" title="Platform Browser - An Open Source Project Hosted by Entilda IT Solutions" href="http://platform.entilda.com"></a><br clear="all" />
<!-- wrapper -->
</div>
</body>
</html>
