<?php
/**
 * @copyright Copyright (C) 2011-2012 The Platform Authors. All rights reserved.
 * @license   GNU/GPL, see LICENSE.php
 * Platform is free software. This version may have been modified pursuant
 * to the GNU General Public License, and as distributed it includes or
 * is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 * See COPYRIGHT.php for copyright notices and details.
 */
?>
<div id="navigation">
<?php platform_launch_path_to($_SERVER['QUERY_STRING']); ?>
</div><!-- navigation -->
