chive:
  - name: "Chive"
  - repository: https://github.com/fusonic/chive.git
mongodb:
  - name: "Mongo DB"
  - repository: https://github.com/mongodb/mongo.git
omnidb:
  - name: "Omni DB"
  - repository: https://github.com/OmniDB/OmniDB.git
sqlpad:
  - name: "SQL Pad"
  - repository: https://github.com/sqlpad/sqlpad.git